name: Go custom action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install dependencies
        run: |
          go install github.com/jstemmer/go-junit-report@latest
      - name: Test
        run: cd go && go test -v ./... 2>&1 | go-junit-report -set-exit-code > report.xml
      - name: Record
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          build_name: $GITHUB_RUN_ID
          report_path: ./go
          test_runner: go-test
          source_path: ./go
        if: always()
